#!/usr/bin/env python
# coding=utf-8

'''
 字典的运算
在数据字典中执行一些计算操作 (比如求最小值、最大值、排序等等)
'''

prices = {
    'ACME': 45.23,
    'AAPL': 612.78,
    'IBM': 205.55,
    'HPQ': 37.20,
    'FB': 10.75
}

min_price = min(zip(prices.values(), prices.keys()))
max_price = max(zip(prices.values(), prices.keys()))

print "min:",min_price
print "max:",max_price


prices_sorted = sorted(zip(prices.values(), prices.keys()))
print
print "min--sort-->max :",prices_sorted

#varchar
print
print "min varchar:",min(prices) # Returns 'AAPL'
print "max varchar:",max(prices) # Returns 'IBM'

#value
print
print "min value:",min(prices.values()) # Returns 10.75
print "max value:",max(prices.values()) # Returns 612.78

#value
print
print "min value:",min(prices, key=lambda k: prices[k]) # Returns 'FB'
print "max value:",max(prices, key=lambda k: prices[k]) # Returns 'AAPL'

min_value = prices[min(prices, key=lambda k: prices[k])]
print
print "min value :",min_value



prices = { 'AAA' : 45.23, 'ZZZ': 45.23 }
print
print "min value :",min(zip(prices.values(), prices.keys()))
print "max value:",max(zip(prices.values(), prices.keys()))

